from __future__ import annotations

class MemoryNode:
    def __init__(self, index: int, memory_type: str, preview: str, topics: list[str], files: list[str]) -> None:
        self.index = index
        self.memory_type = memory_type
        self.preview = preview
        self.topics = topics
        self.files = files

    def signature(self) -> tuple[int, str]:
        return (self.index, self.memory_type)

NODES = [
    MemoryNode(index=0, memory_type='decision', preview='> <goal_context> Continue working toward the active thread goal.  The objective below is user-provided data. Treat it as', topics=['goal', 'work', 'blocked'], files=['FFI/插件改动', 'FFI/插件说明', 'dlopen/dlsym', 'original/user-triggered', 'projects/sci/docs', 'src/ffi.zig', 'src/parser.zig', 'src/plugin.zig', 'src/vm.zig', 'todo.md', '二是权限/插件说明是否真的把', '只有显式能力/运行参数才能穿透', '同时把签名信息用于参数/返回类型', '指针/字节布局和', '继续按照todo.md', '还是需要把安全模型/导出能力继续往前推', '还是需要把返回值/状态码拆成']),
    MemoryNode(index=1, memory_type='decision', preview='> <goal_context> Continue working toward the active thread goal.  The objective below is user-provided data. Treat it as', topics=['goal', 'work', 'blocked'], files=['original/user-triggered', 'projects/sci/docs', '继续按照todo.md']),
    MemoryNode(index=2, memory_type='milestone', preview='> 继续 我会继续按真实 demo 校准实现。现在的关键是让 VM 识别 `@extern` 签名并按实际 `.sa` 里的 `u8/u16/u32/i32/u64/i64/ptr/f32/f64/void` 调用 native 符号，同时', topics=['allow-ffi', 'dlopen', 'extern'], files=['dlopen/dlsym', 'u8/u16/u32/i32/u64/i64/ptr/f32/f64/void']),
    MemoryNode(index=3, memory_type='emotional', preview='> <goal_context> Continue working toward the active thread goal.  The objective below is user-provided data. Treat it as', topics=['goal', 'parse', 'work'], files=['original/user-triggered', 'paren_start/paren_end', 'projects/sci/docs', '我已经确认没有遗留的构建/测试进程', '继续按照todo.md']),
    MemoryNode(index=4, memory_type='decision', preview='> <goal_context> Continue working toward the active thread goal.  The objective below is user-provided data. Treat it as', topics=['goal', 'work', 'blocked'], files=['original/user-triggered', 'projects/sci/docs', '继续按照todo.md']),
    MemoryNode(index=5, memory_type='decision', preview='> <goal_context> Continue working toward the active thread goal.  The objective below is user-provided data. Treat it as', topics=['goal', 'work', 'blocked'], files=['original/user-triggered', 'projects/sci/docs', '继续按照todo.md']),
    MemoryNode(index=6, memory_type='decision', preview='> <goal_context> Continue working toward the active thread goal.  The objective below is user-provided data. Treat it as', topics=['goal', 'work', 'blocked'], files=['dlopen/dlsym', 'original/user-triggered', 'projects/sci/docs', '继续按照todo.md']),
    MemoryNode(index=7, memory_type='decision', preview='> <goal_context> Continue working toward the active thread goal.  The objective below is user-provided data. Treat it as', topics=['goal', 'work', 'blocked'], files=['original/user-triggered', 'projects/sci/docs', '继续按照todo.md', '这样声明过签名的真实插件/API']),
    MemoryNode(index=8, memory_type='decision', preview='> <goal_context> Continue working toward the active thread goal.  The objective below is user-provided data. Treat it as', topics=['goal', 'work', 'blocked'], files=['original/user-triggered', 'projects/sci/docs', '继续按照todo.md']),
    MemoryNode(index=9, memory_type='milestone', preview='> <goal_context> Continue working toward the active thread goal.  The objective below is user-provided data. Treat it as', topics=['demo', 'node', 'projects'], files=['./run_vm_tests.sh', '.local/share/sa_plugins/installed/vm/current', '301/302', 'API_COVERAGE.md', 'Deno/Node', 'README.md', 'bitcast/sext/zext/trunc', 'build/install', 'build/test', 'cache/current', 'client/server', 'create/bind/send/recv/close', 'demo/stdlib', 'demos/标准接口用到的', 'dlopen/dlsym/dlclose', 'dlopen/dlsym/dlclose/dlerror', 'home/vscode/projects/sa_plugins', 'home/vscode/projects/sa_plugins/sa_plugin_vm/API_COVERAGE.md', 'home/vscode/projects/sa_plugins/sa_plugin_vm/README.md', 'home/vscode/projects/sa_plugins/sa_plugin_vm/sap.json', 'home/vscode/projects/sa_plugins/sa_plugin_vm/src/ffi.zig', 'home/vscode/projects/sa_plugins/sa_plugin_vm/src/parser.zig', 'home/vscode/projects/sa_plugins/sa_plugin_vm/src/vm.zig', 'home/vscode/projects/sa_plugins/sa_plugin_vm/tests/http_client_test.sa', 'home/vscode/projects/sci/demos/compare/thread_bench.sa', 'home/vscode/projects/sci/demos/rosetta/184_pthread_spawn_join/main.sa', 'home/vscode/projects/sci/demos/rosetta/186_sqlite_c_api_binding/main.sa', 'http-client/http-server', 'join/drop', 'original/user-triggered', 'parser/VM', 'projects/sci/demos', 'projects/sci/docs', 'pthread_join/drop', 'pthread_spawn/join', 'pthread_spawn/join/drop', 'ptr/i32', 'run_vm_tests.sh', 'sa_node_plugin_dgram_create/bind/send/recv/close', 'sa_plugin_node/node.sal', 'sap.js', 'sci/demos', 'sext/trunc', 'sext/zext/trunc/bitcast', 'src/ffi.zig', 'src/parser.zig', 'src/plugin.zig', 'src/vm.zig', 'tests/test_node_plugin.sa', 'text/plain', 'todo.md', 'vm/current', '只能靠运行目录/外部样本补齐', '客户端/服务端', '执行层实现整数扩展/截断和', '的流式路径和请求头/body', '的调用/内存问题', '继续按照todo.md', '还缺一类指令/ABI', '重新安装/同步']),
]

NODE_TYPES = {'decision': [0, 1, 4, 5, 6, 7, 8], 'emotional': [3], 'milestone': [2, 9]}
NODE_TOPICS = {'allow-ffi': [2], 'blocked': [0, 1, 4, 5, 6, 7, 8], 'demo': [9], 'dlopen': [2], 'extern': [2], 'goal': [0, 1, 3, 4, 5, 6, 7, 8], 'node': [9], 'parse': [3], 'projects': [9], 'work': [0, 1, 3, 4, 5, 6, 7, 8]}
NODE_FILES = {'./run_vm_tests.sh': [9], '.local/share/sa_plugins/installed/vm/current': [9], '301/302': [9], 'API_COVERAGE.md': [9], 'Deno/Node': [9], 'FFI/插件改动': [0], 'FFI/插件说明': [0], 'README.md': [9], 'bitcast/sext/zext/trunc': [9], 'build/install': [9], 'build/test': [9], 'cache/current': [9], 'client/server': [9], 'create/bind/send/recv/close': [9], 'demo/stdlib': [9], 'demos/标准接口用到的': [9], 'dlopen/dlsym': [0, 2, 6], 'dlopen/dlsym/dlclose': [9], 'dlopen/dlsym/dlclose/dlerror': [9], 'home/vscode/projects/sa_plugins': [9], 'home/vscode/projects/sa_plugins/sa_plugin_vm/API_COVERAGE.md': [9], 'home/vscode/projects/sa_plugins/sa_plugin_vm/README.md': [9], 'home/vscode/projects/sa_plugins/sa_plugin_vm/sap.json': [9], 'home/vscode/projects/sa_plugins/sa_plugin_vm/src/ffi.zig': [9], 'home/vscode/projects/sa_plugins/sa_plugin_vm/src/parser.zig': [9], 'home/vscode/projects/sa_plugins/sa_plugin_vm/src/vm.zig': [9], 'home/vscode/projects/sa_plugins/sa_plugin_vm/tests/http_client_test.sa': [9], 'home/vscode/projects/sci/demos/compare/thread_bench.sa': [9], 'home/vscode/projects/sci/demos/rosetta/184_pthread_spawn_join/main.sa': [9], 'home/vscode/projects/sci/demos/rosetta/186_sqlite_c_api_binding/main.sa': [9], 'http-client/http-server': [9], 'join/drop': [9], 'original/user-triggered': [0, 1, 3, 4, 5, 6, 7, 8, 9], 'paren_start/paren_end': [3], 'parser/VM': [9], 'projects/sci/demos': [9], 'projects/sci/docs': [0, 1, 3, 4, 5, 6, 7, 8, 9], 'pthread_join/drop': [9], 'pthread_spawn/join': [9], 'pthread_spawn/join/drop': [9], 'ptr/i32': [9], 'run_vm_tests.sh': [9], 'sa_node_plugin_dgram_create/bind/send/recv/close': [9], 'sa_plugin_node/node.sal': [9], 'sap.js': [9], 'sci/demos': [9], 'sext/trunc': [9], 'sext/zext/trunc/bitcast': [9], 'src/ffi.zig': [0, 9], 'src/parser.zig': [0, 9], 'src/plugin.zig': [0, 9], 'src/vm.zig': [0, 9], 'tests/test_node_plugin.sa': [9], 'text/plain': [9], 'todo.md': [0, 9], 'u8/u16/u32/i32/u64/i64/ptr/f32/f64/void': [2], 'vm/current': [9], '二是权限/插件说明是否真的把': [0], '只有显式能力/运行参数才能穿透': [0], '只能靠运行目录/外部样本补齐': [9], '同时把签名信息用于参数/返回类型': [0], '客户端/服务端': [9], '我已经确认没有遗留的构建/测试进程': [3], '执行层实现整数扩展/截断和': [9], '指针/字节布局和': [0], '的流式路径和请求头/body': [9], '的调用/内存问题': [9], '继续按照todo.md': [0, 1, 3, 4, 5, 6, 7, 8, 9], '还是需要把安全模型/导出能力继续往前推': [0], '还是需要把返回值/状态码拆成': [0], '还缺一类指令/ABI': [9], '这样声明过签名的真实插件/API': [7], '重新安装/同步': [9]}
